_wandb:
    value:
        cli_version: 0.25.1
        e:
            p5ssy8z4c6qhikl0emo4of5lpo7np19u:
                codePath: /home/vsc/LLM_TUNE/structure-stability/code/Knowledge_Distillation_v2.ipynb
                codePathLocal: Knowledge_Distillation_v2.ipynb
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "4031871553536"
                        used: "1715580895232"
                email: jungseonglian@sju.ac.kr
                executable: /home/vsc/LLM_TUNE/structure-stability/venv/venv-stability/bin/python
                git:
                    commit: 0628fce41f6bdd028e7f0a143bfc7bf29c059c8b
                    remote: https://github.com/whyz-dev/structure-stability.git
                gpu: NVIDIA GB10
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 6144
                      name: NVIDIA GB10
                      uuid: GPU-f940b7ff-fb81-022d-8b75-718301052e80
                host: spark-aecc
                memory:
                    total: "128519340032"
                os: Linux-6.17.0-1008-nvidia-aarch64-with-glibc2.39
                program: /home/vsc/LLM_TUNE/structure-stability/code/Knowledge_Distillation_v2.ipynb
                python: CPython 3.10.0
                root: /home/vsc/LLM_TUNE/structure-stability/code
                startedAt: "2026-03-24T09:47:30.418305Z"
                writerId: p5ssy8z4c6qhikl0emo4of5lpo7np19u
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.0
            "5": 0.25.1
            "6": 5.3.0
            "8":
                - 1
            "12": 0.25.1
            "13": linux-aarch64
BATCH_SIZE:
    value: 32
DISTILL_WEIGHT:
    value: 0.1
EMA_DECAY:
    value: 0.999
EMA_USE_FOR_EVAL:
    value: true
EPOCHS:
    value: 100
IMG_SIZE:
    value: 320
LEARNING_RATE:
    value: 0.0003
MIN_LR:
    value: 1e-06
MIXUP_ALPHA:
    value: 0.1
MIXUP_PROB:
    value: 0
NUM_WORKERS:
    value: 16
PATIENCE:
    value: 10
SEED:
    value: 42
STABLE_END_MAX_SEC:
    value: 10
STABLE_END_MIN_SEC:
    value: 9
STABLE_FRAMES_PER_VIDEO:
    value: 2
TTA_CANDIDATES:
    value:
        - - none
        - - none
          - hflip
        - - none
          - hflip
          - crop95
UNSTABLE_FRAMES_MAX:
    value: 3
UNSTABLE_FRAMES_MIN:
    value: 2
UNSTABLE_START_MAX_SEC:
    value: 1
UNSTABLE_START_MIN_SEC:
    value: 0.5
USE_AMP:
    value: true
VIDEO_AUG_CACHE:
    value: true
VIDEO_AUG_ENABLE:
    value: true
WEIGHT_DECAY:
    value: 0.0001
backbone_name:
    value: efficientnetv2_rw_s
dropout:
    value: 0.3
hidden_dim:
    value: 512
mid_dim:
    value: 128
out_dim:
    value: 1
pretrained:
    value: true
